version: "3.7"

name: staging

services:
  coucou: 
    build: https://gitlab.com/antoinebhr/bloc5_vide_grenier.git#develop
    ports:
      - 8002:80
    depends_on:
      - db

  db:
    image: mysql
