version: "3.7"

name: prod

services:
  coucou: 
    build: https://gitlab.com/antoinebhr/bloc5_vide_grenier.git#develop
    environment:
      MYSQL_USER: patati
      MYSQL_HOST: patata
    ports:
      - 8001:80
    depends_on:
      - db

  db:
    image: mysql

